import type { Language } from '../../types/domain.ts';
export interface SoundEntry {
  symbol: string;
  languages: Language[];
  spelling: string;
  example: string;
  russian: string;
  tip: Record<Language, string>;
}
function sound(symbol: string, languages: Language[], spelling: string, example: string, russian: string, ru: string, en: string, es: string): SoundEntry {
  return { symbol, languages, spelling, example, russian, tip: { ru, en, es } };
}
const both: Language[] = ['es', 'en'];
export const sounds: SoundEntry[] = [
  sound(
    'ˈ',
    both,
    '—',
    'cable [ˈkaβle]',
    'ударение перед слогом',
    'Следующий слог ударный.',
    'The following syllable is stressed.',
    'La sílaba siguiente es tónica.',
  ),
  sound(
    'ˌ',
    both,
    '—',
    'pronunciation [prəˌnʌnsiˈeɪʃən]',
    'второстепенное ударение',
    'Слабее основного ударения.',
    'Weaker than primary stress.',
    'Más débil que el acento principal.',
  ),
  sound('ː', ['en'], '—', 'see [siː]', 'долгий звук', 'Удлиняет предшествующий звук.', 'Lengthens the preceding sound.', 'Alarga el sonido anterior.'),
  sound(
    '͡',
    both,
    'ch / ch',
    'chico · cheese [t͡ʃ]',
    'два знака, один слитный звук',
    'Связка объединяет два элемента.',
    'A tie bar joins two elements.',
    'La ligadura une dos elementos.',
  ),
  sound(
    '̯',
    ['es'],
    'i, u в дифтонге',
    'hoy [oi̯]',
    'не отдельный слог',
    'Гласный не образует отдельный слог.',
    'The vowel does not form a separate syllable.',
    'La vocal no forma una sílaba propia.',
  ),
  sound('a', ['es'], 'a', 'casa', 'ориентир: «а»', 'Открытый гласный.', 'Open vowel.', 'Vocal abierta.'),
  sound('e', ['es'], 'e', 'mesa', 'ориентир: «э»', 'Не добавляйте «й».', 'Avoid adding a y glide.', 'No añadas una deslizada.'),
  sound('i', ['es'], 'i', 'sí', 'ориентир: «и»', 'Гласный переднего ряда.', 'Front vowel.', 'Vocal anterior.'),
  sound('o', ['es'], 'o', 'como', 'ориентир: «о»', 'Округлите губы.', 'Round the lips.', 'Redondea los labios.'),
  sound('u', ['es'], 'u', 'tú', 'ориентир: «у»', 'Губы округлены.', 'Rounded lips.', 'Labios redondeados.'),
  sound('ɾ', ['es'], 'r', 'pero', 'короткое «р»', 'Один удар кончика языка.', 'One tongue-tip tap.', 'Un golpe de la punta de la lengua.'),
  sound(
    'r',
    ['es'],
    'rr; r в начале',
    'perro · rojo',
    'раскатистое «р»',
    'Вибрация кончика языка.',
    'Tongue-tip vibration.',
    'Vibración de la punta de la lengua.',
  ),
  sound(
    'β',
    ['es'],
    'b, v в контексте',
    'cable · la vida',
    'между «б» и «в»; не русское «в»',
    'Сблизьте губы без полного смыкания.',
    'Bring lips close without sealing them.',
    'Acerca los labios sin cerrarlos.',
  ),
  sound(
    'ð',
    both,
    'd / th',
    'cada · this',
    'точного русского аналога нет',
    'Легко приблизьте язык к передним зубам; пропускайте воздух с голосом.',
    'Voiced dental sound.',
    'Sonido dental sonoro.',
  ),
  sound(
    'θ',
    both,
    'z, c перед e/i / th',
    'cinco · think',
    'точного русского аналога нет',
    'Расположите кончик языка у передних зубов или между ними; выдувайте воздух без голоса.',
    'Voiceless dental sound.',
    'Sonido dental sordo.',
  ),
  sound(
    'ɣ',
    ['es'],
    'g в контексте',
    'amigo',
    'мягкое по смыканию «г», не «гь»',
    'Задняя часть языка не смыкается полностью.',
    'No complete closure at the back of the tongue.',
    'Sin cierre completo en la parte posterior de la lengua.',
  ),
  sound(
    'x',
    ['es'],
    'j; g перед e/i',
    'jamón · gente',
    'ориентир: «х»',
    'Глухое трение в задней части рта.',
    'Voiceless friction at the back of the mouth.',
    'Fricción sorda en la parte posterior de la boca.',
  ),
  sound('ɲ', ['es'], 'ñ', 'niño', 'ориентир: «нь»', 'Нёбный носовой звук.', 'Palatal nasal.', 'Nasal palatal.'),
  sound(
    'ʝ',
    ['es'],
    'y; ll при yeísmo',
    'yo · calle',
    'ориентир: «й» с более тесным проходом',
    'Звонкий нёбный звук; зависит от региона.',
    'Voiced palatal sound; varies by region.',
    'Sonido palatal sonoro; varía según la región.',
  ),
  sound(
    'j',
    both,
    'i / y',
    'pie · yes',
    'ориентир: «й»',
    'Короткий переход к гласному.',
    'A brief glide into a vowel.',
    'Deslizamiento breve hacia una vocal.',
  ),
  sound(
    'w',
    both,
    'u / w',
    'puerta · we',
    'краткое «у», не «в»',
    'Начните с округлённых губ.',
    'Start with rounded lips.',
    'Empieza con los labios redondeados.',
  ),
  sound(
    'ŋ',
    both,
    'n перед k/g / ng',
    'banco · sing',
    'носовой звук без отдельного «г»',
    'Задняя часть языка касается мягкого нёба.',
    'Back of tongue contacts the soft palate.',
    'La parte posterior de la lengua toca el velo.',
  ),
  sound('t͡ʃ', both, 'ch', 'chico · cheese', 'ориентир: «ч»', 'Один слитный звук.', 'One joined sound.', 'Un sonido unido.'),
  sound('ʃ', ['en'], 'sh', 'ship', 'ориентир: «ш»', 'Глухой шипящий.', 'Voiceless postalveolar fricative.', 'Fricativa postalveolar sorda.'),
  sound('ʒ', ['en'], 's в контексте', 'vision', 'ориентир: «ж»', 'Звонкая пара к [ʃ].', 'Voiced counterpart of [ʃ].', 'Pareja sonora de [ʃ].'),
  sound('d͡ʒ', ['en'], 'j; g в контексте', 'job · giant', 'ориентир: слитное «дж»', 'Одна аффриката.', 'One affricate.', 'Una africada.'),
  sound('ɹ', ['en'], 'r', 'red', 'не раскатывайте русское «р»', 'Без удара кончика языка.', 'No tongue-tip tap.', 'Sin golpe de la punta de la lengua.'),
  sound('h', ['en'], 'h', 'hello', 'лёгкий выдох, не сильное «х»', 'Гортанный звук.', 'Glottal sound.', 'Sonido glotal.'),
  sound(
    'ɪ',
    ['en'],
    'i в контексте',
    'ship',
    'краткий звук между «и» и «ы»',
    'Отличайте от [iː].',
    'Distinguish it from [iː].',
    'Distingue este sonido de [iː].',
  ),
  sound('iː', ['en'], 'ee; ea', 'sheep · see', 'долгое «и» как ориентир', 'Отличайте от [ɪ].', 'Distinguish it from [ɪ].', 'Distingue este sonido de [ɪ].'),
  sound(
    'æ',
    ['en'],
    'a в контексте',
    'cat',
    'открытый звук между «э» и «а»',
    'Раскройте рот шире, чем для [e].',
    'Open wider than for [e].',
    'Abre más la boca que para [e].',
  ),
  sound(
    'ə',
    ['en'],
    'безударные гласные',
    'about',
    'очень краткий нейтральный гласный',
    'Schwa, обычно без ударения.',
    'Schwa, usually unstressed.',
    'Schwa, normalmente átona.',
  ),
  sound(
    'ʌ',
    ['en'],
    'u; o в контексте',
    'cup · love',
    'ориентир: короткое открытое «а»',
    'Не округляйте губы.',
    'Do not round the lips.',
    'No redondees los labios.',
  ),
  sound(
    'ʊ',
    ['en'],
    'oo; u в контексте',
    'book · put',
    'короткое ненапряжённое «у»',
    'Отличайте от [uː].',
    'Distinguish it from [uː].',
    'Distingue este sonido de [uː].',
  ),
  sound('uː', ['en'], 'oo в контексте', 'food', 'долгое «у» как ориентир', 'Отличайте от [ʊ].', 'Distinguish it from [ʊ].', 'Distingue este sonido de [ʊ].'),
  sound(
    'eɪ',
    ['en'],
    'a; ay',
    'day',
    'ориентир: «эй»',
    'Два качества в одном слоге.',
    'Two vowel qualities in one syllable.',
    'Dos cualidades vocálicas en una sílaba.',
  ),
  sound('aɪ', ['en'], 'i; y', 'my', 'ориентир: «ай»', 'Один слог.', 'One syllable.', 'Una sílaba.'),
  sound(
    'əʊ / oʊ',
    ['en'],
    'o; oa',
    'go · boat',
    'ориентир: переход к «у»',
    'Британский / американский вариант.',
    'British / American variant.',
    'Variante británica / estadounidense.',
  ),
  sound(
    'ɒ / ɑː',
    ['en'],
    'o в контексте',
    'lot',
    'открытое «о» / открытое долгое «а»',
    'Вариант зависит от акцента.',
    'The variant depends on the accent.',
    'La variante depende del acento.',
  ),
  sound('ɔː', ['en'], 'aw; or', 'law', 'долгое открытое «о»', 'Округлённый гласный.', 'Rounded vowel.', 'Vocal redondeada.'),
  sound(
    'ɜː / ɝ',
    ['en'],
    'ir; ur; er',
    'bird',
    'точного русского аналога нет',
    'Британский / американский вариант с r-окраской.',
    'British / American r-coloured variant.',
    'Variante británica / estadounidense con coloración de r.',
  ),
];
// Shared entries stay visible regardless of the hint language.
const all: Language[] = ['ru', 'es', 'en'];
sounds.push(
  sound(
    'b',
    all,
    'RU: б · ES: b, v · EN: b',
    'был · boca / vaca (после паузы) · book',
    'звонкое «б»',
    'Сомкните губы, затем откройте их с голосом. В испанском b/v в других позициях часто произносятся без полного смыкания.',
    'Close both lips, then release with voicing. Spanish b/v often have no complete closure in other positions.',
    'Cierra los labios y ábrelos con voz. En otras posiciones, b/v suelen pronunciarse sin cierre completo.',
  ),
  sound(
    'p',
    all,
    'RU: п · ES: p · EN: p',
    'папа · pan · spin',
    'глухое «п»',
    'Сомкните и разомкните губы без голоса. Придыхание зависит от языка и позиции.',
    'Close and release both lips without voicing. Aspiration depends on language and position.',
    'Cierra y abre los labios sin voz. La aspiración depende del idioma y la posición.',
  ),
  sound(
    't',
    all,
    'RU: т · ES: t · EN: t',
    'там · todo · stop',
    'глухое «т»',
    'Смычка передней части языка; место контакта и придыхание зависят от языка.',
    'Make a closure with the front of the tongue; contact position and aspiration depend on language.',
    'Haz un cierre con la parte anterior de la lengua; el contacto y la aspiración dependen del idioma.',
  ),
  sound(
    'd',
    all,
    'RU: д · ES: d · EN: d',
    'дом · dos (после паузы) · day',
    'звонкое «д»',
    'Смычка передней части языка с голосом. В испанском между гласными смыкание обычно неполное.',
    'Make a voiced closure with the front of the tongue. Spanish d usually has incomplete closure between vowels.',
    'Haz un cierre con la parte anterior de la lengua y voz. Entre vocales, la d española suele tener un cierre incompleto.',
  ),
  sound(
    'k',
    all,
    'RU: к · ES: c, qu · EN: k, c',
    'кот · casa / queso · skin',
    'глухое «к»',
    'Сомкните заднюю часть языка с мягким нёбом, затем отпустите без голоса.',
    'Close the back of the tongue against the soft palate, then release without voicing.',
    'Cierra la parte posterior de la lengua contra el velo y suelta sin voz.',
  ),
  sound(
    'ɡ',
    all,
    'RU: г · ES: g, gu · EN: g',
    'год · gato (после паузы) · go',
    'звонкое «г»',
    'Смычка задней части языка с мягким нёбом и голосом.',
    'Make a voiced closure with the back of the tongue against the soft palate.',
    'Haz un cierre con la parte posterior de la lengua contra el velo, con voz.',
  ),
  sound(
    'm',
    all,
    'RU: м · ES: m · EN: m',
    'мама · mano · man',
    'носовое «м»',
    'Губы сомкнуты; воздух проходит через нос с голосом.',
    'Close the lips; voiced air passes through the nose.',
    'Cierra los labios; el aire pasa por la nariz con voz.',
  ),
  sound(
    'n',
    all,
    'RU: н · ES: n · EN: n',
    'нос · no · no',
    'носовое «н»',
    'Сомкните переднюю часть языка; пропускайте воздух через нос с голосом.',
    'Make a closure with the front of the tongue; pass voiced air through the nose.',
    'Cierra con la parte anterior de la lengua; deja pasar el aire por la nariz con voz.',
  ),
  sound(
    'f',
    all,
    'RU: ф · ES: f · EN: f',
    'факт · foto · fine',
    'глухое «ф»',
    'Приблизьте нижнюю губу к верхним зубам и выдувайте воздух без голоса.',
    'Bring the lower lip close to the upper teeth and pass air without voicing.',
    'Acerca el labio inferior a los dientes superiores y deja pasar aire sin voz.',
  ),
  sound(
    'v',
    ['ru', 'en'],
    'RU: в · EN: v',
    'вот · very',
    'звонкое «в»',
    'Нижняя губа у верхних зубов; воздух идёт с голосом. Испанская буква v обычно не обозначает этот звук.',
    'Lower lip near the upper teeth, with voicing. Spanish letter v normally does not represent this sound.',
    'Labio inferior cerca de los dientes superiores, con voz. La letra v española normalmente no representa este sonido.',
  ),
  sound(
    's',
    all,
    'RU: с · ES: s, z/c при seseo · EN: s',
    'сад · sol · see',
    'глухое «с»',
    'Создайте узкий проход передней частью языка; выдувайте воздух без голоса.',
    'Make a narrow channel with the front of the tongue and pass air without voicing.',
    'Forma un canal estrecho con la parte anterior de la lengua y deja pasar aire sin voz.',
  ),
  sound(
    'z',
    ['ru', 'en'],
    'RU: з · EN: z, s',
    'зал · zoo / roses',
    'звонкое «з»',
    'Произнесите щелевой звук с голосом; передняя часть языка образует узкий проход.',
    'Use voicing with a narrow channel formed by the front of the tongue.',
    'Usa la voz con un canal estrecho formado por la parte anterior de la lengua.',
  ),
  sound(
    'l',
    all,
    'RU: л ([ɫ], [lʲ]) · ES: l · EN: l',
    'RU: [ɫ]/[lʲ] · ES: lado · EN: leaf',
    'боковое «л»',
    'Передняя часть языка смыкается; воздух идёт по бокам. Тёмное [ɫ] и мягкое [lʲ] требуют дополнительных знаков.',
    'Make a front tongue closure and pass air along the sides. Dark [ɫ] and palatalized [lʲ] need additional symbols.',
    'Haz un cierre con la parte anterior de la lengua y deja pasar aire por los lados. [ɫ] y [lʲ] requieren signos adicionales.',
  ),
  sound(
    'ʲ',
    ['ru'],
    'смягчение согласной',
    'мел [mʲel]',
    'палатализация',
    'Дополнительный знак: поднимите среднюю часть языка к твёрдому нёбу при произнесении согласного.',
    'An additional mark: raise the tongue body towards the hard palate while making the consonant.',
    'Signo adicional: eleva el cuerpo de la lengua hacia el paladar duro al pronunciar la consonante.',
  ),
);
export function searchSounds(query: string): SoundEntry[] {
  const needle = query.trim().toLocaleLowerCase();
  return sounds.filter(
    (entry) =>
      !needle || [entry.symbol, entry.spelling, entry.example, entry.russian, ...Object.values(entry.tip)].join(' ').toLocaleLowerCase().includes(needle),
  );
}
export function filterSounds(language: Language, query: string): SoundEntry[] {
  const needle = query.trim().toLocaleLowerCase();
  return sounds.filter(
    (entry) =>
      entry.languages.includes(language) &&
      (!needle || [entry.symbol, entry.spelling, entry.example, entry.russian, ...Object.values(entry.tip)].join(' ').toLocaleLowerCase().includes(needle)),
  );
}
export const guideCopy: Record<
  Language,
  {
    language: string;
    search: string;
    symbol: string;
    spelling: string;
    example: string;
    hint: string;
    intro: string;
    practice: string;
    sources: string;
    empty: string;
  }
> = {
  ru: {
    language: 'Язык подсказок',
    search: 'Найти символ, букву или пример',
    symbol: 'Символ IPA',
    spelling: 'Буквы в слове',
    example: 'Пример',
    hint: 'Как произнести',
    intro:
      'IPA обозначает звуки независимо от языка. Символы, написания и примеры ниже — общая база; язык подсказок меняет только объяснение произношения. Это краткая справка, полный алфавит доступен по ссылке. Русские аналоги приблизительны.',
    practice:
      'Прочитайте пример → проверьте положение языка и губ → произнесите фразу целиком. Для звучания отдельных символов откройте интерактивную таблицу IPA.',
    sources: 'Источники и звучание',
    empty: 'Нет подходящих символов. Попробуйте другой запрос или язык.',
  },
  en: {
    language: 'Hint language',
    search: 'Find a symbol, spelling or example',
    symbol: 'IPA symbol',
    spelling: 'Spelling',
    example: 'Example',
    hint: 'How to pronounce',
    intro:
      'IPA represents sounds across languages. Symbols, spellings and examples stay the same; hint language changes only the pronunciation explanation. This is a short guide; the full alphabet is linked below. Russian equivalents are approximate.',
    practice: 'Read the example → check your tongue and lips → say the whole phrase. Use the interactive IPA chart to hear individual symbols.',
    sources: 'Sources and sounds',
    empty: 'No matching symbols. Try another search or language.',
  },
  es: {
    language: 'Idioma de las pistas',
    search: 'Buscar símbolo, letras o ejemplo',
    symbol: 'Símbolo IPA',
    spelling: 'Letras',
    example: 'Ejemplo',
    hint: 'Cómo pronunciar',
    intro:
      'La IPA representa sonidos independientemente del idioma. Los símbolos, letras y ejemplos permanecen; el idioma de las pistas cambia solo la explicación. Esta guía es breve; la tabla completa está enlazada abajo. Los equivalentes rusos son aproximados.',
    practice:
      'Lee el ejemplo → comprueba la lengua y los labios → pronuncia la frase entera. Abre la tabla IPA interactiva para escuchar símbolos individuales.',
    sources: 'Fuentes y sonidos',
    empty: 'No hay símbolos coincidentes. Prueba otra búsqueda o idioma.',
  },
};
